#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# ./MPC/mwc.pl -type make ../CSCI355/CSCI355-CppGeneric
#
#----------------------------------------------------------------------------


all: Generic

depend: Generic-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.Generic $(@)

.PHONY: Generic
Generic:
	@$(MAKE) -f Makefile.Generic all

.PHONY: Generic-depend
Generic-depend:
	@$(MAKE) -f Makefile.Generic depend

project_name_list:
	@echo Generic
